owner: koenbeek # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Web tools
    url: https://www.t00ls.eu
  - name: assets overview
    url: https://assets.t00ls.eu
  - name: Assets API backend
    url: https://assets.t00ls.eu/api/management/health
    __dangerous__body_down_if_text_missing: '"status":"UP"'
  - name: Nextcloud
    url: https://cloud.t00ls.eu
  - name: EU electricity prices
    url: https://el.t00ls.eu    
status-website:
  cname: up.t00ls.eu
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: T00LS Uptime
  introTitle: "T00LS online service upptime"
  introMessage: upptime stats for online services on T00LS.EU
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
